// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Poseidon.Usecases.Company;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace Poseidon.Company.UseCases.GetCompanyUseCase
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class CompaniesResponse
    {
        [JsonProperty("companies")]
        public Companies Companies { get; set; }
    }

    public class Companies
    {
        [JsonProperty("data")]
        public List<Data> Data { get; set; }
    }

    public class Data
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("attributes")]
        public Attributes Attributes { get; set; }
    }

    public class Attributes
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }
    }
}
